### ISSUE TITLE
Support for Buffer/Data Input in addition to URL

### ISSUE THREAD

**Issue by yzajoee** [dictadata/pdf-data-parser#2]
Hello Team,

I'm a user of the pdf-data-parser project and I've found it quite useful for parsing PDF data. However, I've encountered a limitation that I'd like to propose an enhancement for.

Currently, the project only supports passing a URL as input to fetch and parse PDF data. While this works well for many cases, it would be beneficial to have the flexibility to pass a Buffer or raw data directly as input. This is because in some scenarios, users may already have the PDF data in memory as a Buffer or as raw data and it would be more efficient to parse it directly rather than having to write it to a temporary file or serve it over a URL.

I noticed that the underlying pdf.js library does support passing data directly as a configuration option. It would be great if this capability could be exposed in pdf-data-parser as well.

`const parser = new PdfDataParser({data: new Unit8Array(file._data.buffer)})`

**Comment by drewletcher** [comment]
Thanks for the suggestion! I just published version 1.2.10 with this requested enhancement.

### PdfDataParser Options

PdfDataParser constructor takes an options object with the following fields. One of `url` or `data` arguments is required.

`{URL|string} url` - The local path or URL of the PDF document.

`{TypeArray|string} data` - pdf file data in a TypedArray, e.g. `options.data = new Uint8Array(buffer)`.

Common Options:
...
